jobs:
  build-and-deploy:
    environment: user
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Collect Workflow Telemetry
      uses: Nfsaavedra/workflow-telemetry-action@raw_data
      with:
        save_raw_stats: true
    - uses: actions/checkout@main
    - name: Setup Node.js environment
      uses: actions/setup-node@main
      with:
        node-version: 18
    - name: init secrets
      uses: shine1594/secrets-to-env-action@master
      with:
        file_name_prod: .env
        prefix_prod: ''
        secrets: ${{ toJSON(secrets) }}
        secrets_env: production
    - name: init
      run: npm install
    - id: run
      name: run
      uses: nick-fields/retry@master
      with:
        command: npm start
        max_attempts: 3
        timeout_minutes: 10
    - name: Keep Running
      run: 'git config --local user.email "${{ github.actor_id }}+${{ github.actor
        }}@users.noreply.github.com"

        git config --local user.name "${{ github.actor }}"

        git remote set-url origin https://${{ github.actor }}:${{ github.token }}@github.com/${{
        github.repository }}

        git pull --rebase --autostash

        git commit --allow-empty -m "Keep Running..."

        git push

        '
    - name: Delete old workflow run
      uses: Mattraks/delete-workflow-runs@main
      with:
        keep_minimum_runs: 50
        repository: ${{ github.repository }}
        retain_days: 0
        token: ${{ github.token }}
name: Cloud check in action
'on':
- workflow_dispatch
permissions: write-all
